# Generated by Django 3.2.4 on 2021-06-10 23:56

import Marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FilePathField(path=Marketplace.models.image_dir)),
                ('description', models.TextField()),
            ],
        ),
    ]
